

INSERT INTO players (firstName , lastName , teamName)VALUES('DeAndre', 'Bembry', 'Atlanta Hawks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Charles', 'Brown Jr.', 'Atlanta Hawks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Vince', 'Carter', 'Atlanta Hawks');
INSERT INTO players (firstName , lastName , teamName)VALUES('John', 'Collins', 'Atlanta Hawks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Allen', 'Crabbe', 'Atlanta Hawks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jaylen', 'Brown', 'Boston Celtics');
INSERT INTO players (firstName , lastName , teamName)VALUES('Carsen', 'Edwards', 'Boston Celtics');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tacko', 'Fall', 'Boston Celtics');
INSERT INTO players (firstName , lastName , teamName)VALUES('Gordon', 'Hatward', 'Boston Celtics');
INSERT INTO players (firstName , lastName , teamName)VALUES('Romeo', 'Langford', 'Boston Celtics');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jarrett', 'Allen', 'Brooklyn Nets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Wilson', 'Chandler', 'Brooklyn Nets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Nicolas', 'Claxton', 'Brooklyn Nets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Spencer', 'Dinwiddie', 'Brooklyn Nets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kenvin', 'Durant', 'Brooklyn Nets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Dwayne', 'Bacon', 'Charlotte Hornets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Nicolas', 'Batum', 'Charlotte Hornets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bismack', 'Biyombo', 'Charlotte Hornets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Miles', 'Bridges', 'Charlotte Hornets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Robert', 'Franks', 'Charlotte Hornets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Ryan', 'Arcidiacono', 'Chicago Bulls');
INSERT INTO players (firstName , lastName , teamName)VALUES('Wendell', 'Carter Jr.', 'Chicago Bulls');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kris', 'Dunn', 'Chicago Bulls');
INSERT INTO players (firstName , lastName , teamName)VALUES('Cristiano', 'Felicio', 'Chicago Bulls');
INSERT INTO players (firstName , lastName , teamName)VALUES('Daniel', 'Gafford', 'Chicago Bulls');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jordan', 'Clarkson', 'Caveliers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tyler', 'Cook', 'Caveliers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Matthew', 'Dellavedova', 'Caveliers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Darius', 'Garland', 'Caveliers');
INSERT INTO players (firstName , lastName , teamName)VALUES('John', 'Henson', 'Caveliers');
INSERT INTO players (firstName , lastName , teamName)VALUES('J.J', 'Barea', 'Mavericks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Ryan', 'Broekhoff', 'Mavericks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jalen', 'Brunson', 'Mavericks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Antonius', 'Cleveland', 'Mavericks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Seth', 'Curry', 'Mavericks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Will', 'Barton', 'Nuggets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Malik', 'Beasley', 'Nuggets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bol', 'Bol', 'Nuggets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Vlatko', 'Cancar', 'Nuggets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Torrey', 'Craig', 'Nuggets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jordan', 'Bone', 'Pistons');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bruce', 'Brown', 'Pistons');
INSERT INTO players (firstName , lastName , teamName)VALUES('Sekou', 'Doumbouya', 'Pistons');
INSERT INTO players (firstName , lastName , teamName)VALUES('Andre', 'Drummond', 'Pistons');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tim', 'Frazier', 'Pistons');
INSERT INTO players (firstName , lastName , teamName)VALUES('Ky', 'Bowman', ' Warriors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Stephen', 'Curry', ' Warriors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jacob', 'Evans', ' Warriors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Draymond', 'Green', ' Warriors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Damion', 'Lee', ' Warriors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Clint', 'Capela', 'Houston Rockets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Gary', 'Clark', 'Houston Rockets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Chris', 'Clemons', 'Houston Rockets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Eric', 'Gordon', 'Houston Rockets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Gerald', 'Green', 'Houston Rockets');
INSERT INTO players (firstName , lastName , teamName)VALUES('Goga', 'Bitadze', 'Pacers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Malcolm', 'Brogdon', 'Pacers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jusitn', 'Holiday', 'Pacers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Aron', 'Holiday', 'Pacers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Alize', 'Johnson', 'Pacers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Patrick', 'Beverley', 'Los Angeles Clippers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Amir', 'Coffey', 'Los Angeles Clippers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Paul', 'George', 'Los Angeles Clippers');
INSERT INTO players (firstName , lastName , teamName)VALUES('JaMychal', 'Green', 'Los Angeles Clippers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Maurice', 'Harkless', 'Los Angeles Clippers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kostas', 'Antetokounmpo', 'Lakers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Avery', 'Bradley', 'Lakers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tony', 'Bradley', 'Lakers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Alex', 'Caruso', 'Lakers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Lebron', 'James', 'Lakers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Grayson', 'Allen', 'Grizzlies');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kyle', 'Anderson', 'Grizzlies');
INSERT INTO players (firstName , lastName , teamName)VALUES('Dillion', 'Brooks', 'Grizzlies');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bruno', 'Caboclo', 'Grizzlies');
INSERT INTO players (firstName , lastName , teamName)VALUES('Brandon', 'Clarke', 'Grizzlies');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bam', 'Adebayo', 'Heat');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jimmy', 'Butlet', 'Heat');
INSERT INTO players (firstName , lastName , teamName)VALUES('Goran', 'Dragic', 'Heat');
INSERT INTO players (firstName , lastName , teamName)VALUES('Udonis', 'Haslem', 'Heat');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tyler', 'Herro', 'Heat');
INSERT INTO players (firstName , lastName , teamName)VALUES('Giannis', 'Antetokounmpo', 'Bucks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Thanasis', 'Antetokounmpo', 'Bucks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Dragan', 'Bender', 'Bucks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Eric', 'Bledsoe', 'Bucks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Sterling', 'Brown', 'Bucks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Keita', 'Bates-Diop', 'Timberwolves');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jordan', 'Bell', 'Timberwolves');
INSERT INTO players (firstName , lastName , teamName)VALUES('Robert', 'Convington', 'Timberwolves');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jarrett', 'Culver', 'Timberwolves');
INSERT INTO players (firstName , lastName , teamName)VALUES('Gorgui', 'Dieng', 'Timberwolves');
INSERT INTO players (firstName , lastName , teamName)VALUES('Nickei', 'Alexander-Walker', 'Pelicans');
INSERT INTO players (firstName , lastName , teamName)VALUES('Lonzo', 'Ball', 'Pelicans');
INSERT INTO players (firstName , lastName , teamName)VALUES('Zylan', 'Cheatham', 'Pelicans');
INSERT INTO players (firstName , lastName , teamName)VALUES('Derrick', 'Favors', 'Pelicans');
INSERT INTO players (firstName , lastName , teamName)VALUES('Josh', 'Gray', 'Pelicans');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kadeem', 'Allen', 'Knicks');
INSERT INTO players (firstName , lastName , teamName)VALUES('RJ', 'Barrett', 'Knicks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Ignas', 'Brazdeikis', 'Knicks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Reggie', 'Bullock', 'Knicks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Damyean', 'Dotson', 'Knicks');
INSERT INTO players (firstName , lastName , teamName)VALUES('Steven', 'Adams', 'Thunder');
INSERT INTO players (firstName , lastName , teamName)VALUES('Darius', 'Bazley', 'Thunder');
INSERT INTO players (firstName , lastName , teamName)VALUES('Deonte', 'Burton', 'Thunder');
INSERT INTO players (firstName , lastName , teamName)VALUES('Hamidou', 'Diallo', 'Thunder');
INSERT INTO players (firstName , lastName , teamName)VALUES('Luguentz', 'Dort', 'Thunder');
INSERT INTO players (firstName , lastName , teamName)VALUES('Al-Farouq', 'Aminu', 'Magic');
INSERT INTO players (firstName , lastName , teamName)VALUES('D.J', 'Augustin', 'Magic');
INSERT INTO players (firstName , lastName , teamName)VALUES('Mo', 'Bamba', 'Magic');
INSERT INTO players (firstName , lastName , teamName)VALUES('Khem', 'Birch', 'Magic');
INSERT INTO players (firstName , lastName , teamName)VALUES('Michael', 'Carter-Williams', 'Magic');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jonah', 'Bolden', '76ers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Trey', 'Burke', '76ers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Joel', 'Embiid', '76ers');
INSERT INTO players (firstName , lastName , teamName)VALUES('James', 'Ennis III', '76ers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Joel', 'Embiid', '76ers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Deandre', 'Ayton', 'Suns');
INSERT INTO players (firstName , lastName , teamName)VALUES('Aron', 'Baynes', 'Suns');
INSERT INTO players (firstName , lastName , teamName)VALUES('Devin', 'Booker', 'Suns');
INSERT INTO players (firstName , lastName , teamName)VALUES('Mikal', 'Bridges', 'Suns');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jevon', 'Carter', 'Suns');
INSERT INTO players (firstName , lastName , teamName)VALUES('Carmelo', 'Anthony', 'Trail Blazers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Kent', 'Bazemore', 'Trail Blazers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Moses', 'Brown', 'Trail Blazers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Zach', 'Collins', 'Trail Blazers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Mario', 'Hezonja', 'Trail Blazers');
INSERT INTO players (firstName , lastName , teamName)VALUES('Trevor', 'Ariza', 'Kings');
INSERT INTO players (firstName , lastName , teamName)VALUES('Marvin', 'Bagley III', 'Kings');
INSERT INTO players (firstName , lastName , teamName)VALUES('Harrison', 'Barnes', 'Kings');
INSERT INTO players (firstName , lastName , teamName)VALUES('Nemamja', 'Bjelica', 'Kings');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bogdan', 'Bogdanovic', 'Kings');
INSERT INTO players (firstName , lastName , teamName)VALUES('LaMarcus', 'Aldridge', 'Spurs');
INSERT INTO players (firstName , lastName , teamName)VALUES('Marco', 'Belinelli', 'Spurs');
INSERT INTO players (firstName , lastName , teamName)VALUES('DeMarre', 'Carroll', 'Spurs');
INSERT INTO players (firstName , lastName , teamName)VALUES('DeMar', 'DeRozan', 'Spurs');
INSERT INTO players (firstName , lastName , teamName)VALUES('Drew', 'Eunbanks', 'Spurs');
INSERT INTO players (firstName , lastName , teamName)VALUES('OG', 'Anunoby', 'Raptors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Chris', 'Boucher', 'Raptors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Oshae', 'Brissett', 'Raptors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Terence', 'Davis', 'Raptors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Marc', 'Gasol', 'Raptors');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bojan', 'Bogdanovic', 'Jazz');
INSERT INTO players (firstName , lastName , teamName)VALUES('Tony', 'Bradley', 'Jazz');
INSERT INTO players (firstName , lastName , teamName)VALUES('Jarrell', 'Brantley', 'Jazz');
INSERT INTO players (firstName , lastName , teamName)VALUES('Mike', 'Conley', 'Jazz');
INSERT INTO players (firstName , lastName , teamName)VALUES('Ed', 'Davis', 'Jazz');
INSERT INTO players (firstName , lastName , teamName)VALUES('Bradley', 'Beal', 'Wizards');
INSERT INTO players (firstName , lastName , teamName)VALUES('Davis', 'Bertans', 'Wizards');
INSERT INTO players (firstName , lastName , teamName)VALUES('Isaac', 'Bonga', 'Wizards');
INSERT INTO players (firstName , lastName , teamName)VALUES('Troy', 'Brown Jr.', 'Wizards');
INSERT INTO players (firstName , lastName , teamName)VALUES('Thomas', 'Bryant', 'Wizards');




SELECT*FROM players;
